### ISSUE TITLE
Whisper as local api

### ISSUE THREAD

**Issue by pablodegrande** [savbell/whisper-writer#1]
Would it be possible to use local api instead of web api?

**Comment by savbell** [comment]
Great question! I just added the option to run a Whisper model locally instead of using the API in [my most recent commit](https://github.com/savbell/whisper-writer/commit/dc7c8a7b0a5bae7e177b0cd0f69c806f84b88853). It is fairly slow though (at least for me) so you may need to adjust some configuration options or the model being used. Hope this helps! 😊
