### ISSUE TITLE
Could not load library cudnn_ops_infer64_8.dll. (Windows)

### ISSUE THREAD

**Issue by KernAlan** [savbell/whisper-writer#29]
```
Could not load library cudnn_ops_infer64_8.dll. Error code 126
Please make sure cudnn_ops_infer64_8.dll is in your library path!
```

Tried on Windows 10 and 11.

**Comment by KernAlan** [comment]
Ah, the problem is that `local_model_options` was set to auto by default. I set it to `cpu` instead and this solved the issue.

If anyone knows where the CUDA dependencies are being called, I will gladly put in some error handling if needed.

**Comment by savbell** [comment]
Hi, thanks for the bug report! :)

The local model is created here: https://github.com/savbell/whisper-writer/blob/main/src/transcription.py#L27-L31

I imagine the error comes from it auto-defaulting to GPU and not having these libraries installed: https://github.com/SYSTRAN/faster-whisper#requirements

If you wanted to add some error handling, that would be fantastic! Otherwise I'll add a note in the Readme in my next commit. Thanks again!

**Comment by KernAlan** [comment]
Thank you! Submitted a PR: https://github.com/savbell/whisper-writer/pull/30

This project is wonderful by the way. I plan to use it to make my prompting faster.

**Comment by savbell** [comment]
Thanks for your help! I've just merged the PR :)

I'm glad you're finding the project useful! It's always cool when something you make just for yourself ends up being something other people find helpful, too!
