### ISSUE TITLE
Whisper-writer Popup Stuck on "Recording" After Transcription

### ISSUE THREAD

**Issue by murtaza-nasir** [savbell/whisper-writer#49]
Thank you for the fantastic whisper-writer app! I got CUDA working thanks to the helpful reply in [#33](https://github.com/savbell/whisper-writer/issues/33#issue-2122905439)

I have the app set to record only when I press the default key combo. After transcription, the popup switches back to "Recording" even though I'm not recording. It stays there until closed manually.

Has anyone else faced this issue? Any help would be appreciated.

**Comment by savbell** [comment]
Hi, thank you for your issue! I'm glad you were able to get CUDA working.

When you say you have the app set to record only when you press the default key combo, which recording mode exactly do you have set?

In the latest update, I added a new recording mode called `continuous` which is the new default. It's expected behaviour to start recording again after transcribing until the activation key combo is pressed again. The other modes — `voice_activity_detection`, `press_to_toggle`, and `hold_to_record` — should not do this. Are you running into this problem with one of them?

Thanks,
Sav

**Comment by murtaza-nasir** [comment]
I am using `hold_to_record`. 

I turned on "hide status window" to get rid of the recording/transcribing notification, but I noticed another issue in this case. Now I see that the recording keeps on going after transcribing, even with `hold_to_record`. The terminal window shows "Recording...", the windows notification tray has a recording indication ("Python is using your microphone") but the app seems to be recording into the void and not transcribing anything. Now when I press the recording key combo, it records something but the output is gibberish like "You are a very good listener. You are a very good listener. You are a very good listener. You are a very good listener. You are a very good listener. You are a very good listener. You are a very good listener. You are a very good listener. You are a very good listener. You are a very good listener. You are a very good listener. You are a very good listener. You are a very good listener. You are a very good listener. "

**Comment by murtaza-nasir** [comment]
Thank you so much for the quick fixes! The lingering status notification bug has been fixed! Haven't tried to replicate the other issue, since it was only happening when I was enabling the hide status window option, which I am not doing now.
