### ISSUE TITLE
Issue with Numba.jit

### ISSUE THREAD

**Issue by Jason-K** [savbell/whisper-writer#6]
G:\Git clones\AI\whisper-writer\venv\Lib\site-packages\whisper\timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
Traceback (most recent call last):
  File "G:\Git clones\AI\whisper-writer\src\main.py", line 94, in <module>
    config = load_config_with_defaults()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Git clones\AI\whisper-writer\src\main.py", line 52, in load_config_with_defaults
    user_config = json.load(config_file)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 12 column 21 (char 265)

**Comment by savbell** [comment]
Hi, thanks for your comment! The Numba deprecation warning is a [known issue](https://github.com/savbell/whisper-writer#known-issues) with the current version of the Whisper Python package. They have since fixed it (https://github.com/openai/whisper/commit/7ca9fbea86987a11266c0a6205bc284c089e5fbc), so it should not be an issue once the next version is released. You can safely ignore the warning.

If the program isn't running because of this issue (or if it's just really annoying), you can manually update the Python package to use the latest commit from the [Whisper repository](https://github.com/openai/whisper) by running the following commands:
```
pip uninstall openai-whisper
pip install git+https://github.com/openai/whisper.git 
```

I hope this helps! :)

**Comment by savbell** [comment]
Updated Whisper package in [my latest commit](https://github.com/savbell/whisper-writer/commit/5c10f6b84817d11cffbcdff1ab3f483819c41544), resolving this issue.
